### ISSUE TITLE
Code to obtain ground truth depth maps for network training?

### ISSUE THREAD

**Issue by prstrive** [QT-Zhu/AA-RMVSNet#1]
Hi, thanks for your work. Could you please provide a high-resolution depth map like CascadeMVS (https://github.com/alibaba/cascade-stereo)? Or would you consider releasing the code for obtaining the depth map?

**Comment by QT-Zhu** [comment]
We only generate low-res ground truth depth maps. The main principle is to cross-filter unreliable points. You may turn to AttMVS to get more details as mentioned in the paper.
