### ISSUE TITLE
Tanks and temples 结果

### ISSUE THREAD

**Issue by VILmchen** [QT-Zhu/AA-RMVSNet#10]
您好，我看AA-RMVSNet在Tanks and Temples数据集上的表现非常好，麻烦咨询一下如何复现AA-RMVSNet在Tanks and Temples的leaderboard上的结果呢

**Comment by QT-Zhu** [comment]
We have already released the code for evaluation on Tanks and Temples. You need to finetune the DTU-trained model on BlendedMVS for best performance.

**Comment by VILmchen** [comment]
Thanks for your reply. After the finetune on BlendedMVS, are there any hyper-parameters that need to change for the Tanks and Temples, such as depth intervals or photo_threshold?

**Comment by QT-Zhu** [comment]
Using the script provided will be just fine.

**Comment by VILmchen** [comment]
Thanks. Is there any plan to release the finetuned model?

**Comment by QT-Zhu** [comment]
Yes. Actually we planned to release the model in Jan. 2021, but the team members are all busy and have no leissure to test. So... please be patient.

**Comment by VILmchen** [comment]
OK, thanks!
