### ISSUE TITLE
Questions about testing BlendesMVS

### ISSUE THREAD

**Issue by pdw211** [QT-Zhu/AA-RMVSNet#11]
Hello, I tested blended_MVS before, using the model you gave me. The GPU is 3090, but the memory of the GPU is insufficient when executing the test script. How do you set the test parameters and get the results

**Comment by QT-Zhu** [comment]
With the given information I cannot know what happens exactly to you... Maybe check the batchsize since the defaulted setting is with multiple GPUs.

**Comment by pdw211** [comment]
> With the given information I cannot know what happens exactly to you... Maybe check the batchsize since the defaulted setting is with multiple GPUs.

I just want to ask about the parameter settings of the test blended dataset
