### ISSUE TITLE
NaN value in testing

### ISSUE THREAD

**Issue by mazeyu** [QT-Zhu/AA-RMVSNet#13]
When running the testing script, I found nan values occur in the computation, thus giving all 0 output depth. What are possible reasons? Thanks

**Comment by QT-Zhu** [comment]
Which dataset are you evaluating? Have you modified some parameters of the script?

**Comment by mazeyu** [comment]
Both DTU and T&T. No modification

**Comment by QT-Zhu** [comment]
That's strange. Have you checked your pytorch version? Or maybe the dataset itself is different?

**Comment by mazeyu** [comment]
After switching to the exact pytorch version you use, it works, though not fully knowing the underlying reason. Thanks
