### ISSUE TITLE
Error when running testing 

### ISSUE THREAD

**Issue by BiaBibii** [QT-Zhu/AA-RMVSNet#14]
I tried to run eval.sh and get this error, with both DTU and TNT:

RuntimeError: Error(s) in loading state_dict for AARMVSNet:
	Missing key(s) in state_dict: "feature.init_conv.0.0.weight", "feature.init_conv.0.0.bias",.....
Unexpected key(s) in state_dict: "module.feature.init_conv.0.0.weight"...

When I trained, I changed the view_num from 7 to 2 and batch size to 1, because of memory and time (I'm running in colab).

**Comment by QT-Zhu** [comment]
It is a common problem caused by DataParallel. Manually adding "module." to each key in the dict variable will be just fine.

**Comment by BiaBibii** [comment]
Thanks a lot. It works.
