### ISSUE TITLE
question about sample details？

### ISSUE THREAD

**Issue by DIVE128** [QT-Zhu/AA-RMVSNet#15]
Hello, thank you for your great work and generous contribution.  There‘re two details in code: (1)  in the script(train_dtu.sh), # make
sure num_depth* interval = 203.45. (2) in t&t datasets, the depths are reversed. What's the role of these two operations？

**Comment by QT-Zhu** [comment]
It's confusing and complicated to explain indeed. DTU gives a fixed depth range for each view, so the most ideal way to deliver the dataset is to give the min depth as well as the max depth and let users to apply their own ways of depth division. However, the dataset (or to say, the preprocessed version) assumes a default `D`, so it gives the depth interval instead (2.5mm in the text). As a result, if we want to change the value of `D`, we need to leverage a new parameter to scale the interval to make sure the range of depth is still the same.

I suppose you are referring to the flag of `inverse_depth`. It is an advantage with recurrent regularization, and you can check the paper of R-MVSNet for details.

**Comment by DIVE128** [comment]
Thank you a lot
