### ISSUE TITLE
About numdepth and interval_scale

### ISSUE THREAD

**Issue by Innocence4822** [QT-Zhu/AA-RMVSNet#16]
Hello, I'm sorry to bother you. I want to ask why the numdepth and intervalscale values set in the code are like this? ‘

> d=150

> interval_scale=1.35 #make sure d * interval_scale = 203.52

Why is what is said in the paper different from that in the code?

![image](https://user-images.githubusercontent.com/59044733/158922721-979701cb-9c7c-45d9-9b00-eb4e30b6f449.png)

**Comment by QT-Zhu** [comment]
Please refer to #15 for explanation. I set `d=150` for users who do not have a GPU with enough memory (24GB).

**Comment by Innocence4822** [comment]
> 

I see. Thank you for your reply
