### ISSUE TITLE
Whether the benchmarking on Tanks and Temples use fine-tuned model on the training set of BlendedMVS.

### ISSUE THREAD

**Issue by MiZhenxing** [QT-Zhu/AA-RMVSNet#2]
Hi, thank you for your excellent work. 
I have a question about the model used for tanks and temples. In your paper, you said that

![微信截图_20210824200801](https://user-images.githubusercontent.com/34396974/130613669-edd431e6-80dd-4661-be74-4f50c200e569.png)

So I wonder whether you also used fine-tuned model on the training set of BlendedMVS for benchmarking on Tanks and Temples or not. Thank you!

**Comment by QT-Zhu** [comment]
Yes, you're correct.

**Comment by MiZhenxing** [comment]
Thank you very much!
