### ISSUE TITLE
Load your existing model to continue training

### ISSUE THREAD

**Issue by lemonsstyle** [QT-Zhu/AA-RMVSNet#21]
Hello, thank you for your contribution. I tested your network in the tnt dataset, and the result is very good. But when you say "Note that the newly released pretrained models are not compatible with the old codebase. Please update the code as well."  , I have downloaded the latest entire code file. Why do I still report an error when I load your ckpt? 
————————————————————————
Missing key(s) in state_dict: 
"module.feature.init_conv.0.0.weight", "module.feature.init_conv.0.0.bias", "module.feature.init_conv.0.1.weight", "module.feature.init_conv.0.1.bias", "module.feature.init_conv.1.0.weight", "module.feature.init_conv.1.0.bias", 
......

Unexpected key(s) in state_dict: 
"cost_regularization.cell_list.0.conv.weight", "cost_regularization.cell_list.0.conv.bias", "cost_regularization.cell_list.1.conv.weight", "cost_regularization.cell_list.1.conv.bias", "cost_regularization.cell_list.2.conv.weight", "cost_regularization.cell_list.2.conv.bias", 
......
————————————————————————
My device is ubuntu 20.04, torch 1.12.0, cuda 11.4, python 3.7.0, RTX 3090

**Comment by QT-Zhu** [comment]
I have only tested the ckpt for running evaluation but I can provide a possible solution.
If you compare all the keys (missing and unexpected) carefully, you'll find the only difference is all missing keys start with "module." so a direct solution is to manually add "module." to all the keys. This problem is very common for PyTorch and is caused by DataParallel.

**Comment by lemonsstyle** [comment]
Sorry, I went to check after receiving your message. Maybe it was because I modified the network structure a little bit and chose to load your model, so the parameter  was wrong : ).Thank you for your answer! I did something else two days ago. I didn't remember to reply to you until now...

**Comment by QT-Zhu** [comment]
It's totally fine. Feel free to reach out if you have further questions.
