### ISSUE TITLE
make sure d * interval_scale = 203.52

### ISSUE THREAD

**Issue by dazaier** [QT-Zhu/AA-RMVSNet#25]
你好，我看到训练脚本文件中有这样一句注释：make sure d * interval_scale = 203.52。我想请问下满足这个条件的意义是什么呀？然后我还想请问下interval_scale这个变量的作用是什么，没有太搞懂。能麻烦解答下吗，多谢了。

**Comment by QT-Zhu** [comment]
这是DTU数据集预处理的历史遗留问题，详见 #15 。
