### ISSUE TITLE
Ground Truth improvement code

### ISSUE THREAD

**Issue by vkvats** [QT-Zhu/AA-RMVSNet#26]
Hi, 
Thank you for this amazing repo. I am really curious about improvement in the ground truth depth maps. You mention that it is similar to Attention aware multi-view stereo paper by Luo et al. 2020. I am unable to find the code that was used for it. can you please point me to the relevant code for GT improvement? 

Thanks,

**Comment by QT-Zhu** [comment]
Hello. Sorry I have no idea whether there is a published implementation for this. But this data preparation is simple: just run the same depth filtering procedure to GT depth maps as is normally done to predicted depth maps, so that the incorrect part of the GT depth maps will be filtered.
