### ISSUE TITLE
Batch size and timing for single GPU setup

### ISSUE THREAD

**Issue by KevinCain** [QT-Zhu/AA-RMVSNet#3]
First, let me add my thanks for your excellent work.

With a single GPU setup, I infer that I should set 'batch=1' in 'env.sh'. Is that correct?

Using the default parameters with batch size of 1, computing depth for DTU models takes ~170 seconds per image on a single GPU (nVidia 1060).

Does that seem correct?

**Comment by QT-Zhu** [comment]
We set the batchsize of inferene at `scripts/eval_dtu.sh`. If you set this in `env.sh`, I doubt it would be overwritten by 2 since `env.sh` is executed before. 
For inference, 170 seconds are longer than our experiments, but considering 1060 is a relative old model, it makes sense to me, as long as the prediction depth map is correct.

**Comment by KevinCain** [comment]
Thanks for your response. To answer you, the depth maps and fusion steps work fine based on the resulting .ply mesh.

Could you provide a few reference timings? I'd like to explore your technique but the timing I see is is orders of magnitude longer than MVS-Net and variants which unfortunately makes testing impractical.

**Comment by QT-Zhu** [comment]
For DTU evaluation, the inference time for one image is around 40 seconds. Since you can increase the batchsize, the averaged inference time could be reduced to 20+ seconds. Since RNN regularization trades time for space, time is indeed a bottleneck.

**Comment by KevinCain** [comment]
Thank you @QT-Zhu for relaying a general sense of your evaluation times, and your elegant point that time and space are once again entangled properties. ;-) On a practical level, I'm eager to do a few tests on a more capable system.

I also want to express my thanks for packaging your code in a succinct, easy to follow way. It is one of the few deep learning projects that compiled the first time!
