### ISSUE TITLE
相机参数估计的问题

### ISSUE THREAD

**Issue by WeiCaike** [QT-Zhu/AA-RMVSNet#6]
很抱歉打扰到您了，最近使用您的代码实现MVSNet的深度估计时 ，遇到了很难解决的问题，想请教一下。
在获取相机内外参数时使用了colmap（https://github.com/colmap/colmap/tree/3.5）来估计的，然后使用caolmap2mvsnet.py 将colmap估计的结果转换成MVSNet的输入格式。
目前问题是colmap估计的内外参和真值差距很大。下图是输入DTU数据时colmap估计的结果
![image](https://user-images.githubusercontent.com/48276224/140451372-dfbdb80d-ad7b-4756-80cb-8c2669006dec.png)
下图是DTU提供的直
![image](https://user-images.githubusercontent.com/48276224/140451445-119de7d6-0f7e-4274-b652-ee3c849a2751.png)
数据差异很大。
并且当使用估计的内外参作为网络输入时，输出的深度估计完全不正确。请问有什么解决方法吗？
谢谢！

**Comment by QT-Zhu** [comment]
相机的内外参矩阵刻画的是世界坐标系到相机坐标系、相机坐标系到图像坐标系的变换，因此根据坐标系选取的不同，自然也不唯一，这不会影响重建的结果，但是会影响点云的评测（因为DTU使用给定的坐标系进行评测）。关于使用COLMAP重新标定的内外参运行，虽然您没有提供足够的细节，但是我猜想应该无外乎两个问题：一是相机文件读取时候搞错了最小深度、分层区间、最大深度这些数据；二是我们的运行脚本是基于MVSNet的深度划分进行的，因此不适用，需要修改一些参数。

**Comment by WeiCaike** [comment]
> 相机的内外参矩阵刻画的是世界坐标系到相机坐标系、相机坐标系到图像坐标系的变换，因此根据坐标系选取的不同，自然也不唯一，这不会影响重建的结果，但是会影响点云的评测（因为DTU使用给定的坐标系进行评测）。关于使用COLMAP重新标定的内外参运行，虽然您没有提供足够的细节，但是我猜想应该无外乎两个问题：一是相机文件读取时候搞错了最小深度、分层区间、最大深度这些数据；二是我们的运行脚本是基于MVSNet的深度划分进行的，因此不适用，需要修改一些参数。

感谢您的及时回复和帮助，我再重新查看一下关于以上的这个两个问题。谢谢！
