### ISSUE TITLE
test in Tank and Temple benchmark

### ISSUE THREAD

**Issue by lilipopololo** [QT-Zhu/AA-RMVSNet#7]
I success using eval.sh and generate "intermediate" point cloud by fusion.sh.
Can you remind me  how to submit these data to tank and temple website .**Because I don't have ***.log file**, so I guess to use ***.log file in TAT databenchmark from mvsnet.
I just try to upload data to TAT ,can you help me ?
![image](https://user-images.githubusercontent.com/29367450/142219321-e5af962b-80d2-4cf7-90d9-a80f020b3125.png)

**Comment by QT-Zhu** [comment]
Yes, just use those provided by MVSNet since you are also adopting its camera calibration.

For instructions of uploading, you are supposed to follow this [official website](https://www.tanksandtemples.org/uploadpreparations/).

**Comment by lilipopololo** [comment]
thank&nbsp;you&nbsp;for&nbsp;your&nbsp;reply


---Original---
From: &quot;Qingtian ***@***.***&gt;
Date: Thu, Nov 18, 2021 00:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QT-Zhu/AA-RMVSNet] test in Tank and Temple benchmark (Issue #7)




 
Yes, just use those provided by MVSNet since you are also adopting its camera calibration.
 
For instructions of uploading, you are supposed to follow this official website.
 
&mdash;

**Comment by lilipopololo** [comment]
I&nbsp;notice&nbsp;eval.sh&nbsp;generate&nbsp;2&nbsp;kind&nbsp;of&nbsp;depth&nbsp;map(960*544&nbsp;1024*544&nbsp;perhaps?).these&nbsp;maps&nbsp;aren't&nbsp;the&nbsp;same&nbsp;size&nbsp;as&nbsp;images&nbsp;in&nbsp;databenchmark&nbsp;from&nbsp;mvsnet.
Maybe&nbsp;the&nbsp;internal&nbsp;parameter&nbsp;matrix&nbsp;should&nbsp;multiply&nbsp;scales&nbsp;parameter?I&nbsp;realy&nbsp;confused&nbsp;about&nbsp;this&nbsp;point.


---Original---
From: &quot;Qingtian ***@***.***&gt;
Date: Thu, Nov 18, 2021 00:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QT-Zhu/AA-RMVSNet] test in Tank and Temple benchmark (Issue #7)




 
Yes, just use those provided by MVSNet since you are also adopting its camera calibration.
 
For instructions of uploading, you are supposed to follow this official website.
 
&mdash;

**Comment by BiaBibii** [comment]
hello, sorry for bothering you,  @lilipopololo how did you obtained .log files?
