### ISSUE TITLE
Question about the survey paper

### ISSUE THREAD

**Issue by XYZ-qiyh** [QT-Zhu/AA-RMVSNet#9]
Hello, Dr. @QT-Zhu 
Recently, I'm reading your survey paper, "Deep Learning for Multi-view Stereo via Plane Sweep: A Survey". 
I found the Fig. 2 of the paper is visually appealing and understandable. 
Now I want to make photos of plane sweeping using my own 3D scene and 2D images, how could I achieve it?
Could you give me some suggestions?
Looking forward to your reply.
![PlaneSweepingStereo](https://user-images.githubusercontent.com/45621782/144400064-fb8f603f-f824-43c8-983e-4b356c02acbf.png)

**Comment by QT-Zhu** [comment]
Hi, I'm still a master student lol. Actually this image is a simple imitation of a lecture PPT (maybe from a foreign college, I forget). There is no such fancy technique. I just render three images and arrange them manually.

**Comment by XYZ-qiyh** [comment]
Thanks for your reply.
